server:
  port: 10086
spring:
  application:
    name: ly-registry
eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 4000 # This is not required
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
