server:
  port: 10010
spring:
  application:
    name: api-gateway
zuul:
  prefix: /api #添加路由前缀
  routes:
    item-service: /item/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
  ignored-services:
    - upload-service # 忽略upload-service服务
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 熔断超时时长
ribbon:
  connectionTimeout: 10000 #ribbon 链接超时时长
  readTimeout: 10000 # ribbon 读取超时时长
#  MaxAutoRetries: 0 # 当前服务重试次数
#  MaxAutoRetriesNextServer: 0 # 切换服务重试次数


