server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot
    username: root
    password: root
eureka:
  client:
#        fetch-registry: false
#        register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
